default:
  navigation:
    - title: Chiles
      subtitle: Categories
      url: /t/categories/chiles
      items:
        - :title: Chiles
          :url: /t/categories/chiles
      promo_banners:
        - subtitle: New collection
          title: Summer 2021
          url: /t/new-collection/summer-2021
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-percent-off
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Salsas
      subtitle: Categories
      url: /t/categories/salsas
      items:
        - :title: Salsas
          :url: /t/categories/salsas
        - :title: Adobos
          :url: /t/categories/adobos
        - :title: Sazonadores
          :url: /t/categories/sazonadores
      promo_banners:
        - subtitle: New collection
          title: Summer 2021
          url: /t/new-collection/summer-2021
          image: 'meganav/promo_banner_left-second-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-percent-off
          image: 'meganav/promo_banner_right-second-category.jpg'
    - title: Dulces
      subtitle: Categories
      url: /t/categories/dulces
      items:
        - :title: Dulces
          :url: /t/categories/dulces
      promo_banners:
        - subtitle: New collection
          title: Summer 2021
          url: /t/new-collection/summer-2021
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-percent-off
          image: 'meganav/promo_banner_right-third-category.jpg'
    - title: Botanas
      subtitle: Categories
      url: /t/categories/botanas
      items:
        - :title: Botanas
          :url: /t/categories/botanas
      promo_banners:
        - subtitle: New collection
          title: Summer 2021
          url: /t/new-collection/summer-2021
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-percent-off
          image: 'meganav/promo_banner_right-third-category.jpg'
    - title: Especias
      subtitle: Categories
      url: /t/categories/especias
      items:
        - :title: Especias
          :url: /t/categories/especias
      promo_banners:
        - subtitle: New collection
          title: Summer 2021
          url: /t/new-collection/summer-2021
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-percent-off
          image: 'meganav/promo_banner_right-third-category.jpg'
    - title: Variedad
      subtitle: Categories
      url: /t/categories/variedad
      items:
        - :title: Variedad
          :url: /t/categories/variedad
      promo_banners:
        - subtitle: New collection
          title: Summer 2021
          url: /t/new-collection/summer-2021
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-percent-off
          image: 'meganav/promo_banner_right-third-category.jpg'
    
    - title: Juguetes
      subtitle: Categories
      url: /t/categories/juguetes
      items:
        - :title: Juguetes
          :url: /t/categories/juguetes
      promo_banners:
        - subtitle: New collection
          title: Summer 2021
          url: /t/new-collection/summer-2021
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-percent-off
          image: 'meganav/promo_banner_right-third-category.jpg'
    
fr:
  navigation:
    - title: Femmes
      url: /fr/t/Categories
      promo_banners:
        - subtitle: Nouvelle collection
          title: Été 2021
          url: /fr/t/new-collection/summer-2021
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Offres spéciales
          url: /fr/t/special-offers/30-percent-off
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Hommes
      url: /fr/t/categories
      promo_banners:
        - subtitle: Nouvelle collection
          title: Été 2021
          url: /fr/t/new-collection/summer-2021
          image: 'meganav/promo_banner_left-second-category.jpg'
        - subtitle: Offres spéciales
          url: /fr/t/special-offers/30-percent-off
          image: 'meganav/promo_banner_right-second-category.jpg'
    - title: Vêtecategoriests de sport
      url: /fr/t/categories
      promo_banners:
        - subtitle: Nouvelle collection
          title: Été 2021
          url: /fr/t/new-collection/summer-2021
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Offres spéciales
          url: /fr/t/special-offers/30-percent-off
          image: 'meganav/promo_banner_right-third-category.jpg'
