default:
  navigation:
    - title: Chiles
      subtitle: Categories
      url: /t/categories/chiles
      items:
        - :title: Chiles
          :url: /t/categories/chiles
      promo_banners:
        - subtitle: Chiles
          title: Chiles
          url: /t/categories/chiles
          image: 'meganav/Chiles-2.jpg'
        - subtitle: Mi Costenita
          title: Productos
          url: /t/Categories/
          image: 'meganav/dulces_3.jpg'
    - title: Salsas
      subtitle: Categories
      url: /t/categories/salsas
      items:
        - :title: Salsas
          :url: /t/categories/salsas
        - :title: Adobos
          :url: /t/categories/adobos
        - :title: Sazonadores
          :url: /t/categories/sazonadores
      promo_banners:
        - subtitle: Salsas Yola
          title: Salsas
          url: /t/categories/salsas
          image: 'meganav/Salsas-2.jpg'
        - subtitle: Adobos
          title: Adobos
          url: /t/categories/adobos
          image: 'meganav/adobo-2.jpg'
        - subtitle: Sazonadores
          title: Sazonadores
          url: /t/categories/sazonadores
          image: 'meganav/sazonador.jpg'
    - title: Dulces
      subtitle: Categories
      url: /t/categories/dulces
      items:
        - :title: Dulces
          :url: /t/categories/dulces
      promo_banners:
        - subtitle: Dulces
          title: Dulces
          url: /t/categories/dulces
          image: 'meganav/Dulces-2.jpg'
        
    - title: Botanas
      subtitle: Categories
      url: /t/categories/botanas
      items:
        - :title: Botanas
          :url: /t/categories/botanas
      promo_banners:
        - subtitle: Botanas
          title: Botanas
          url: /t/categories/botanas
          image: 'meganav/Botanas-1.jpg'
        
    - title: Especias
      subtitle: Categories
      url: /t/categories/especias
      items:
        - :title: Especias
          :url: /t/categories/especias
      promo_banners:
        - subtitle: Especias
          title: Especias
          url: /t/categories/especias
          image: 'meganav/Especias-1.jpg'
        
    - title: Variedad
      subtitle: Categories
      url: /t/categories/variedad
      items:
        - :title: Variedad
          :url: /t/categories/variedad
      promo_banners:
        - subtitle: Variedad
          title: Variedad
          url: /t/categories/variedad
          image: 'meganav/Variedad.jpg'
        
    
    - title: Juguetes
      subtitle: Categories
      url: /t/categories/juguetes
      items:
        - :title: Juguetes
          :url: /t/categories/juguetes
      promo_banners:
        - subtitle: Juguetes
          title: Juguetes
          url: /t/categories/juguetes
          image: 'meganav/Jugetes-2.jpg'
        
    
fr:
  navigation:
    - title: Femmes
      url: /fr/t/Categories
      promo_banners:
        - subtitle: Nouvelle collection
          title: Été 2021
          url: /fr/t/new-collection/summer-2021
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Offres spéciales
          url: /fr/t/categories/30-percent-off
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Hommes
      url: /fr/t/categories
      promo_banners:
        - subtitle: Nouvelle collection
          title: Été 2021
          url: /fr/t/new-collection/summer-2021
          image: 'meganav/promo_banner_left-second-category.jpg'
        - subtitle: Offres spéciales
          url: /fr/t/categories/30-percent-off
          image: 'meganav/promo_banner_right-second-category.jpg'
    - title: Vêtecategoriests de sport
      url: /fr/t/categories
      promo_banners:
        - subtitle: Nouvelle collection
          title: Été 2021
          url: /fr/t/new-collection/summer-2021
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Offres spéciales
          url: /fr/t/categories/30-percent-off
          image: 'meganav/promo_banner_right-third-category.jpg'
